spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    service-url:
      defaultZone: http://16.171.53.185:8081/eureka
service:
  product: http://16.171.53.185:8083
  user: http://16.171.53.185:8084
  sale: http://16.171.53.185:8085
  order: http://16.171.53.185:8086
