spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://mysqldb:3306/microservice-ecommerce?createDatabaseIfNotExist=true
    username: root
    password: kemane
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: https://fac663e1-96ac-42be-ad4d-3c1a7512c0d9-10-244-28-23-8081.spch.r.killercoda.com/eureka #http://10.0.0.2:30081/eureka with docker use port 8081 with k8s 30081

