spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://mysqldb:3306/microservice-ecommerce?createDatabaseIfNotExist=true
    username: root
    password: kemane
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: https://2de2d963-f68a-4dc9-92d0-a9b01a87114b-10-244-28-97-30081.spch.r.killercoda.com/eureka

