spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    service-url:
      defaultZone: https://db245a4f-ffaa-43ac-a3fe-f9e0228c9b5e-10-244-29-233-30081.spch.r.killercoda.com/eureka
service:
  product: https://db245a4f-ffaa-43ac-a3fe-f9e0228c9b5e-10-244-29-233-30083.spch.r.killercoda.com
  user: https://db245a4f-ffaa-43ac-a3fe-f9e0228c9b5e-10-244-29-233-30084.spch.r.killercoda.com
  sale: https://db245a4f-ffaa-43ac-a3fe-f9e0228c9b5e-10-244-29-233-30085.spch.r.killercoda.com
  order: https://db245a4f-ffaa-43ac-a3fe-f9e0228c9b5e-10-244-29-233-30086.spch.r.killercoda.com
