spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    service-url:
      defaultZone: http://13.50.101.245:8081/eureka
service:
  product: http://13.50.101.245:8083
  user: http://13.50.101.245:8084
  sale: http://13.50.101.245:8085
  order: http://13.50.101.245:8086
