spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://16.16.90.247:3306/microservice-ecommerce?createDatabaseIfNotExist=true
    username: root
    password: kemane
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://16.16.90.247:8081/eureka

