spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://mysqldb:3306/microservice-ecommerce?createDatabaseIfNotExist=true
    username: root
    password: kemane
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: https://e38ee09b-2d5c-4578-86f9-3e59b217d29a-10-244-29-242-30081.spch.r.killercoda.com/eureka

