spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    service-url:
      defaultZone: http://13.48.226.196:8081/eureka
service:
  product: http://13.48.226.196:8083
  user: http://13.48.226.196:8084
  sale: http://13.48.226.196:8085
  order: http://13.48.226.196:8086
